services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
  redis:
    image: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"