spring:
  application:
    name: sboot-insurance-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always

app:
  redis:
    time-to-live: 30

server:
  port: 8080